spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybasket
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

logging:
  level:
    root: INFO